# Generated by Django 4.2.11 on 2025-01-11 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_impression', models.CharField(choices=[('en_attente', 'En attente'), ('imprimé', 'Imprimé'), ('recupéré', 'Recupéré')], default='en_attente', max_length=20)),
                ('impression_pour', models.CharField(choices=[('Examen', 'Examen'), ('Cours', 'Cours'), ('Document', 'Document')], max_length=10)),
                ('departement', models.CharField(choices=[("Direction d'Étude", "Direction d'Étude (DE)"), ("Direction des Relations d'Entreprises", "Direction des Relations d'Entreprises (DRE)"), ('Recherche & Développement', 'Recherche & Développement (R&D)'), ('Direction des Relations Internationales', 'Direction des Relations Internationales (DRI)'), ("Laboratoire d'Expertise et de Contrôle", "Laboratoire d'Expertise et de Contrôle (LEC)"), ('Career Center', 'Career Center (CC)'), ('Scolarité', 'Scolarité (SC)'), ('Administration', 'Administration (ADM)'), ('IT', 'IT'), ('Direction Générale', 'Direction Générale (DG)')], default="Direction d'Étude", max_length=50)),
                ('filiere', models.CharField(choices=[('Informatique & Management des systèmes', 'Informatique & Management des systèmes (IMS)'), ('Génie Industriel Logistique Internationale', 'Génie Industriel Logistique Internationale (GI-LI)'), ('Génie Industriel Textile - Habillement', 'Génie Industriel Textile - Habillement (GI-TH)'), ('Génie Industriel Chef de Produit', 'Génie Industriel Chef de Produit (GI-CP)'), ('Génie Industriel - Tronc commun', 'Génie Industriel - Tronc commun (GI-TC)'), ('Ingénierie des Textiles techniques et Intelligents', 'Ingénierie des Textiles techniques et Intelligents (ITTI)'), ('Chimie et traitements des matériaux', 'Chimie et traitements des matériaux (CTM)'), ('Master Spécialisé Management Produit Textile-Habillement', 'Master Spécialisé Management Produit Textile-Habillement (MS-MPTH)'), ('Master Spécialisé E-logistique', 'Master Spécialisé E-logistique (MS-E-Log)'), ('Master Spécialisé Distribution et Merchandising', 'Master Spécialisé Distribution et Merchandising (MS-DM)'), ('Master Spécialisé Hygiène, Sécurité Et Environnement', 'Master Spécialisé Hygiène, Sécurité Et Environnement (MS-HSE)'), ('Licence Professionnelle Développement En Habillement', 'Licence Professionnelle Développement En Habillement (LP-DH)'), ('Licence Professionnelle Gestion De Production En Habillement', 'Licence Professionnelle Gestion De Production En Habillement (LP-GPH)'), ('Licence Professionnelle Gestion De Production Textile', 'Licence Professionnelle Gestion De Production Textile (LP-GPT)'), ('Licence Professionnelle Gestion De La Chaine Logistique', 'Licence Professionnelle Gestion De La Chaine Logistique (LP-GCL)'), ('Licence Professionnelle Gestion Achat & Sourcing', 'Licence Professionnelle Gestion Achat & Sourcing (LP-GAS)'), ('Cycle Technicien Spécialisé', 'Cycle Technicien Spécialisé (CTS)'), ('RSA (Rien à signaler)', 'RSA (Rien à signaler)')], max_length=255)),
                ('n_copies', models.IntegerField(default=1)),
                ('format', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='Blanc/Noir', max_length=10)),
                ('couleur', models.CharField(choices=[('Blanc/Noir', 'Blanc/Noir'), ('Couleurs', 'Couleurs')], default='Blanc/Noir', max_length=10)),
                ('recto_verso', models.CharField(choices=[('recto', 'Recto'), ('recto-verso', 'Recto-Verso')], default='recto', max_length=20)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code_validation', models.CharField(blank=True, max_length=4, null=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
