# Generated by Django 5.1.2 on 2024-10-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='/home/linux/Digital_Copy_Center/accounts/templates/reset/password_reset_subject.txt', upload_to='documents/'),
        ),
    ]
