# Generated by Django 5.1.2 on 2024-11-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_alter_document_validation_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recto_verso',
            field=models.CharField(choices=[('recto', 'Recto'), ('recto-verso', 'Recto-Verso')], default='recto', max_length=20),
        ),
    ]
