# Generated by Django 5.1.2 on 2024-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_document_recto_verso'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='code_validation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='validation_impression',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('imprimé', 'Imprimé'), ('recupéré', 'Recupéré')], default='en_attente', max_length=20),
        ),
    ]
