# Generated by Django 5.1.2 on 2025-01-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_document_seen_alter_document_couleur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='seen',
        ),
    ]
