# Generated by Django 4.2.11 on 2025-01-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_remove_document_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='recto_verso',
            field=models.CharField(choices=[('Recto', 'Recto'), ('Recto-Verso', 'Recto-Verso')], default='recto', max_length=20),
        ),
    ]
