# Generated by Django 5.1.2 on 2024-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('direction', 'Direction'), ('professor', 'Professor')], max_length=20),
        ),
    ]
