# Generated by Django 5.1.2 on 2024-11-07 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0005_alter_document_validation_impression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved_by_professor', models.BooleanField(default=False)),
                ('approval_token', models.CharField(max_length=100, unique=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professors.document')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
