# Generated by Django 5.1.2 on 2025-01-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
